services:
  rag-app:
    build: .
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - ./app/vector_store:/app/vector_store
    environment:
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - CLOUDFLARED_TOKEN=${CLOUDFLARED_TOKEN}
    networks:
      - rag-net
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    depends_on:
      - rag-app
    networks:
      - rag-net
    restart: unless-stopped

networks:
  rag-net:
    name: rag-net
 